# Generated by Django 3.2.7 on 2021-10-23 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0002_item_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='imageUrl',
            field=models.CharField(default='image', max_length=250),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(default='Item', max_length=60),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='item',
            name='url',
            field=models.CharField(default='url', max_length=250),
        ),
    ]
