# Generated by Django 3.2.7 on 2021-09-28 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('itemID', models.AutoField(primary_key=True, serialize=False)),
                ('userId', models.IntegerField()),
                ('url', models.CharField(max_length=250)),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.users')),
            ],
        ),
    ]
