# Generated by Django 3.2.7 on 2021-10-12 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_remove_items_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='name',
            field=models.CharField(default='item', max_length=100),
        ),
        migrations.AddField(
            model_name='items',
            name='price',
            field=models.CharField(default='$0.00', max_length=12),
        ),
        migrations.AddField(
            model_name='items',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
