# Generated by Django 3.2.7 on 2021-10-22 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_auto_20211019_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='description',
            field=models.CharField(default='description', max_length=250),
        ),
    ]
