# Generated by Django 3.2.7 on 2021-10-23 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_items_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='items',
            name='priority',
            field=models.CharField(default='0', max_length=25),
        ),
    ]
